//go:build ignore

// Code generated by ooo samples; DO NOT EDIT.
// This file requires external dependencies not included in ooo.
// To use: go get github.com/benitogf/auth github.com/benitogf/ko

// Package main demonstrates JWT authentication with auth package.
// This example shows how to:
// - Add JWT authentication to ooo server
// - Protect routes with token verification
// - Handle user registration and login
// - Use layered storage with ko for persistent user data
//
// Requires: go get github.com/benitogf/auth github.com/benitogf/ko
package main

import (
	"log"
	"net/http"
	"time"

	"github.com/benitogf/auth"
	"github.com/benitogf/ko"
	"github.com/benitogf/ooo"
	"github.com/benitogf/ooo/storage"
	"github.com/gorilla/mux"
)

func main() {
	// Auth storage for users using layered storage with ko persistence
	authStore := storage.New(storage.LayeredConfig{
		Memory:   storage.NewMemoryLayer(),
		Embedded: ko.NewEmbeddedStorage("./auth_data"),
	})

	// Create JWT auth with 10 minute token expiry
	tokenAuth := auth.New(
		auth.NewJwtStore("your-secret-key", time.Minute*10),
		authStore,
	)

	// Create server with static mode
	server := ooo.Server{Static: true}

	// Audit middleware - check JWT for protected routes
	server.Audit = func(r *http.Request) bool {
		// Public routes
		if r.URL.Path == "/register" || r.URL.Path == "/authorize" {
			return true
		}
		// Protected routes require valid token
		return tokenAuth.Verify(r)
	}

	// Enable data routes
	server.OpenFilter("data/*")

	// Add auth routes (/register, /authorize, /verify)
	server.Router = mux.NewRouter()
	tokenAuth.Router(&server)

	server.Start("0.0.0.0:8800")
	log.Println("Server running with JWT auth")
	log.Println("POST /register - register user")
	log.Println("POST /authorize - login and get token")
	log.Println("GET /data/* - protected route (requires token)")
	server.WaitClose()
}
