//go:build ignore

// Code generated by ooo samples; DO NOT EDIT.
// This file requires external dependencies not included in ooo.
// To use: go get github.com/benitogf/pivot

// Package main demonstrates a node server that syncs with a pivot.
// Node servers replicate data from the pivot and can accept local writes
// that sync back when connectivity is restored (AP distributed system).
//
// Requires: go get github.com/benitogf/pivot
package main

import (
	"log"

	"github.com/benitogf/ooo"
	"github.com/benitogf/ooo/storage"
	"github.com/benitogf/pivot"
)

func main() {
	server := &ooo.Server{}
	server.Storage = storage.New(storage.LayeredConfig{Memory: storage.NewMemoryLayer()})

	// Configure pivot synchronization
	config := pivot.Config{
		Keys: []pivot.Key{
			{Path: "settings"}, // Single item sync
			{Path: "items/*"},  // List sync
		},
		NodesKey: "nodes/*",        // Node discovery path
		PivotIP:  "localhost:8800", // Address of the pivot server
	}

	// Setup pivot - modifies server routes and storage hooks
	pivot.Setup(server, config)

	server.Start("0.0.0.0:8801")
	log.Println("Node server running on :8801, syncing with pivot at localhost:8800")
	server.WaitClose()
}
