//go:build ignore

// Code generated by ooo samples; DO NOT EDIT.
// This file requires external dependencies not included in ooo.
// To use: go get github.com/benitogf/pivot

// Package main demonstrates a pivot server (central coordinator).
// The pivot server is the source of truth that nodes sync with.
// Run this first, then start node servers pointing to this address.
//
// Requires: go get github.com/benitogf/pivot
package main

import (
	"log"

	"github.com/benitogf/ooo"
	"github.com/benitogf/ooo/storage"
	"github.com/benitogf/pivot"
)

func main() {
	server := &ooo.Server{}
	server.Storage = storage.New(storage.LayeredConfig{Memory: storage.NewMemoryLayer()})

	// Configure pivot synchronization
	config := pivot.Config{
		Keys: []pivot.Key{
			{Path: "settings"}, // Single item sync
			{Path: "items/*"},  // List sync
		},
		NodesKey: "nodes/*", // Node discovery path
		PivotIP:  "",        // Empty = this is the pivot server
	}

	// Setup pivot - modifies server routes and storage hooks
	pivot.Setup(server, config)

	server.Start("0.0.0.0:8800")
	log.Println("Pivot server running on :8800")
	server.WaitClose()
}
