//go:build ignore

// Code generated by ooo samples; DO NOT EDIT.
// This file requires external dependencies not included in ooo.
// To use: go get github.com/benitogf/nopog

// Custom HTTP endpoints with PostgreSQL storage using nopog.
// This example shows how to:
// - Use nopog for large-scale PostgreSQL storage
// - Use server.Endpoint() for typed API documentation in the explorer UI
// - Query by field, range, and glob patterns
//
// Requires: go get github.com/benitogf/nopog
// Requires: PostgreSQL running on localhost
package main

import (
	"encoding/json"
	"log"
	"net/http"
	"strconv"

	"github.com/benitogf/nopog"
	"github.com/benitogf/ooo"
	"github.com/benitogf/ooo/key"
	"github.com/gorilla/mux"
)

// Product represents an item in the catalog
type Product struct {
	Name     string `json:"name"`
	Category string `json:"category"`
	Price    int    `json:"price"`
}

// ProductResponse includes the key in the response
type ProductResponse struct {
	Key      string `json:"key"`
	Name     string `json:"name"`
	Category string `json:"category"`
	Price    int    `json:"price"`
}

// CreateResponse is returned after creating a product
type CreateResponse struct {
	Created int64  `json:"created"`
	Key     string `json:"key"`
}

func main() {
	// PostgreSQL storage for large-scale persistent data
	db := &nopog.Storage{
		Name:     "mydb",
		Host:     "localhost",
		User:     "postgres",
		Password: "postgres",
	}
	if err := db.Start(); err != nil {
		log.Fatal("Failed to connect:", err)
	}
	defer db.Close()

	// Create table (idempotent)
	if err := db.CreateTable("catalog"); err != nil {
		log.Fatal(err)
	}

	server := ooo.Server{
		Static: true,
		Name:   "Nopog PostgreSQL Demo",
	}

	// List and create products endpoint
	server.Endpoint(ooo.EndpointConfig{
		Path:        "/api/products",
		Description: "List all products or create a new product",
		Methods: ooo.Methods{
			"GET": ooo.MethodSpec{
				Response: []ProductResponse{},
			},
			"POST": ooo.MethodSpec{
				Request:  Product{},
				Response: CreateResponse{},
			},
		},
		Handler: func(w http.ResponseWriter, r *http.Request) {
			switch r.Method {
			case "GET":
				results, err := db.Get("catalog", "products/*")
				if err != nil {
					http.Error(w, err.Error(), 500)
					return
				}
				json.NewEncoder(w).Encode(results)

			case "POST":
				var p Product
				if err := json.NewDecoder(r.Body).Decode(&p); err != nil {
					http.Error(w, err.Error(), 400)
					return
				}
				data, _ := json.Marshal(p)
				productKey := key.Build("products/*")
				ts, err := db.Set("catalog", productKey, string(data))
				if err != nil {
					http.Error(w, err.Error(), 500)
					return
				}
				w.WriteHeader(http.StatusCreated)
				json.NewEncoder(w).Encode(CreateResponse{Created: ts, Key: productKey})
			}
		},
	})

	// Search products by category
	server.Endpoint(ooo.EndpointConfig{
		Path:        "/api/products/search",
		Description: "Search products by category using JSONB field query",
		Params:      ooo.Params{"category": "Product category to filter by"},
		Methods: ooo.Methods{
			"GET": ooo.MethodSpec{
				Response: []ProductResponse{},
			},
		},
		Handler: func(w http.ResponseWriter, r *http.Request) {
			category := r.URL.Query().Get("category")
			results, err := db.GetByField("catalog", "products/*", "category", category)
			if err != nil {
				http.Error(w, err.Error(), 500)
				return
			}
			json.NewEncoder(w).Encode(results)
		},
	})

	// Get recent products by timestamp range
	server.Endpoint(ooo.EndpointConfig{
		Path:        "/api/products/recent",
		Description: "Get recent products by timestamp range (microseconds)",
		Params: ooo.Params{
			"from":  "Start timestamp in microseconds",
			"to":    "End timestamp in microseconds",
			"limit": "Maximum number of results (default: 10)",
		},
		Methods: ooo.Methods{
			"GET": ooo.MethodSpec{
				Response: []ProductResponse{},
			},
		},
		Handler: func(w http.ResponseWriter, r *http.Request) {
			from, _ := strconv.ParseInt(r.URL.Query().Get("from"), 10, 64)
			to, _ := strconv.ParseInt(r.URL.Query().Get("to"), 10, 64)
			limit, _ := strconv.Atoi(r.URL.Query().Get("limit"))
			if limit == 0 {
				limit = 10
			}
			results, err := db.GetNRange("catalog", "products/*", from, to, limit)
			if err != nil {
				http.Error(w, err.Error(), 500)
				return
			}
			json.NewEncoder(w).Encode(results)
		},
	})

	// Delete a product by ID
	server.Endpoint(ooo.EndpointConfig{
		Path:        "/api/products/{id}",
		Description: "Delete a product by its UUID",
		Methods: ooo.Methods{
			"DELETE": ooo.MethodSpec{},
		},
		Handler: func(w http.ResponseWriter, r *http.Request) {
			id := mux.Vars(r)["id"]
			if err := db.Del("catalog", "products/"+id); err != nil {
				http.Error(w, err.Error(), 500)
				return
			}
			w.WriteHeader(http.StatusNoContent)
		},
	})

	server.Start("0.0.0.0:8800")
	log.Println("Server running on :8800 with PostgreSQL backend")
	log.Println("")
	log.Println("Visit http://localhost:8800 to see endpoints in the storage explorer")
	server.WaitClose()
}
