//go:build ignore

// Code generated by ooo samples; DO NOT EDIT.
// This file requires external dependencies not included in ooo.
// To use: go get github.com/benitogf/ko

// Package main demonstrates using ko for persistent storage.
// This example shows how to:
// - Use ko as a persistent storage backend
// - Data survives server restarts
//
// Requires: go get github.com/benitogf/ko
package main

import (
	"log"

	"github.com/benitogf/ko"
	"github.com/benitogf/ooo"
	"github.com/benitogf/ooo/storage"
)

func main() {
	// Create persistent storage with LevelDB backend
	store := &ko.Storage{Path: "./data"}
	err := store.Start([]string{}, nil)
	if err != nil {
		log.Fatal(err)
	}

	// Consume storage broadcast channel (required)
	go storage.WatchStorageNoop(store)

	// Create server with persistent storage
	server := ooo.Server{
		Storage: store,
	}

	server.Start("0.0.0.0:8800")
	log.Println("Server running with persistent storage at ./data")
	server.WaitClose()
}
